### PR TITLE
Big rewrite!

### PR DESCRIPTION
**Pull request by benjaminwood**
Hey @pythonicrubyist, thanks for your work on this gem! I'm using the gem on a client project and ran into a few issues which lead me to some refactoring. A few goals:
1. Fix a few bugs I ran into. The main one being a powerpoint warning that the generated .pptx files needed to be repaired.
2. Try to simplify things in general.
3. Make use of ERB for xml templates/views.

A couple things to note:
1. According to the latest version of powerpoint, SVG is not a supported file format. I've removed it from the specs for now.
2. If no image coordinates are given, it'll now calculate a (somewhat) sane placement for the image. This feature could still use some work, but it's pretty close.

I've tested the generated files on powerpoint 2016 for mac and on keynote (Yosemite). If you/anybody else can test on other software, that'd be great!

To my knowledge I haven't broken any public API. I'd like to write some more useful tests, but I wanted to open this PR to get some feedback.

Thoughts so far?

### CODE REVIEW

**Comment by benjaminwood** [comment]
@pythonicrubyist can you have a look at this? Thanks!

**Comment by pythonicrubyist** [comment]
@benjaminwood , Thanks for your contribution.
I have merged your code. I will do some father testing today and let you know the result.

**Comment by benjaminwood** [comment]
@pythonicrubyist cool, thanks!

**Comment by pythonicrubyist** [comment]
Great job @benjaminwood , thanks for your valuable contribution.

I tested it and all looks good. 

Your changes are all merged to master and today I published the new gem version 1.6 which includes your contribution.

**Pull request merged**
