### PR TITLE
Basic table support

### PR DESCRIPTION
**Pull request by danielsousaio**
* **Adds basic table support**, currently limited to cells text.

* New add_table_slide in _Powerpoint::Presentation_, takes those params:
    `title` , a _String_
    `content` , a 2 dimensions _Array_

* Content is a two-dimensional array of objects that convert to
individual cells by mapping each to a row and column.
  Example:
   ` [['Row1ColA', 'Row1ColB'], ['Row2ColA', 'Row2ColB']]`

* Title is a string for the slide title

* The view is based on `textual_slide.xml.erb`, the generated slide has a
  title on top and a table in the center of the slide. By default each
  cell has lightgrey background.

* Passing tests on `test_spec.rb`, as an example itself.

### CODE REVIEW

**Comment by danielsousaio** [comment]
Suggestions for future improvement:
- Options for cell colors and sizings
- Table positioning
- Multiple tables
- Borders styling

**Comment by danielsousaio** [comment]
**Seems like this feature has a side effect:**
- 3rd slide title gets out of position every time. Doesn't matter what slide it is.

Mind perhaps taking a look at it? Maybe I'm missing something else to integrate the feature in your gem correctly. I'm sorry, but I'm not being able to find the  issue. If anything please tell me what else is needed and I'll kindly do it.

**Steps to reproduce:**
```ruby
# Creating an introduction slide
title = 'Slide1 title'
subtitle = 'Slide1 subtitle'
add_intro title, subtitle

# Creating a text-only slide
title = 'Slide2 title'
content = ['Lorem ipsum']
add_textual_slide title, content

# Creating a text-only slide
# This one's title will break, with this tables feature
title = 'Slide3 title'
content = ['Lorem ipsum']
add_textual_slide title, content
```
**What I have tried so far**

I have tried a vimdiff of both **ppt/slides/slide3.xml** and didn't find a single difference.

Here's a **diff** of the zips, showing sizes of each file:

`➜ diff -y <(unzip -l bad.pptx) <(unzip -l good.pptx) --suppress-common-lines`
```
Archive:  bad.pptx                                            | Archive:  good.pptx
     3437  2017-07-06 18:27   [Content_Types].xml             |      3437  2017-07-06 18:29   [Content_Types].xml
        0  2017-07-06 18:27   ppt/                            |         0  2017-07-06 18:29   ppt/
        0  2017-07-06 18:27   ppt/slides/                     |         0  2017-07-06 18:29   ppt/slides/
     2138  2017-07-06 18:27   ppt/slides/slide3.xml           |      2138  2017-07-06 18:29   ppt/slides/slide3.xml
        0  2017-07-06 18:27   ppt/slides/_rels/               |         0  2017-07-06 18:29   ppt/slides/_rels/
      314  2017-07-06 18:27   ppt/slides/_rels/slide3.xml.rel |       314  2017-07-06 18:29   ppt/slides/_rels/slide3.xml.rel
      314  2017-07-06 18:27   ppt/slides/_rels/slide2.xml.rel |       314  2017-07-06 18:29   ppt/slides/_rels/slide2.xml.rel
      314  2017-07-06 18:27   ppt/slides/_rels/slide1.xml.rel |       314  2017-07-06 18:29   ppt/slides/_rels/slide1.xml.rel
        0  2017-07-06 18:27   ppt/slides/_rels/./             |         0  2017-07-06 18:29   ppt/slides/_rels/./
     2138  2017-07-06 18:27   ppt/slides/slide2.xml           |      2138  2017-07-06 18:29   ppt/slides/slide2.xml
     2098  2017-07-06 18:27   ppt/slides/slide1.xml           |      2098  2017-07-06 18:29   ppt/slides/slide1.xml
        0  2017-07-06 18:27   ppt/slides/./                   |         0  2017-07-06 18:29   ppt/slides/./
     4582  2017-07-06 18:27   ppt/presentation.xml            |      4582  2017-07-06 18:29   ppt/presentation.xml
        0  2017-07-06 18:27   ppt/slideLayouts/               |         0  2017-07-06 18:29   ppt/slideLayouts/
     1728  2017-07-06 18:27   ppt/slideLayouts/slideLayout7.x |      1728  2017-07-06 18:29   ppt/slideLayouts/slideLayout7.x
     3078  2017-07-06 18:27   ppt/slideLayouts/slideLayout11. |      3078  2017-07-06 18:29   ppt/slideLayouts/slideLayout11.
     2854  2017-07-06 18:27   ppt/slideLayouts/slideLayout10. |      2854  2017-07-06 18:29   ppt/slideLayouts/slideLayout10.
     4545  2017-07-06 18:27   ppt/slideLayouts/slideLayout4.x |      4545  2017-07-06 18:29   ppt/slideLayouts/slideLayout4.x
     4490  2017-07-06 18:27   ppt/slideLayouts/slideLayout9.x |      4490  2017-07-06 18:29   ppt/slideLayouts/slideLayout9.x
     7056  2017-07-06 18:27   ppt/slideLayouts/slideLayout5.x |      7056  2017-07-06 18:29   ppt/slideLayouts/slideLayout5.x
     7410  2017-07-06 18:27   ppt/slideLayouts/slideLayout1.x |      7410  2017-07-06 18:29   ppt/slideLayouts/slideLayout1.x
     2066  2017-07-06 18:27   ppt/slideLayouts/slideLayout6.x |      2066  2017-07-06 18:29   ppt/slideLayouts/slideLayout6.x
        0  2017-07-06 18:27   ppt/slideLayouts/_rels/         |         0  2017-07-06 18:29   ppt/slideLayouts/_rels/
      311  2017-07-06 18:27   ppt/slideLayouts/_rels/slideLay |       311  2017-07-06 18:29   ppt/slideLayouts/_rels/slideLay
      311  2017-07-06 18:27   ppt/slideLayouts/_rels/slideLay |       311  2017-07-06 18:29   ppt/slideLayouts/_rels/slideLay
      311  2017-07-06 18:27   ppt/slideLayouts/_rels/slideLay |       311  2017-07-06 18:29   ppt/slideLayouts/_rels/slideLay
      311  2017-07-06 18:27   ppt/slideLayouts/_rels/slideLay |       311  2017-07-06 18:29   ppt/slideLayouts/_rels/slideLay
      311  2017-07-06 18:27   ppt/slideLayouts/_rels/slideLay |       311  2017-07-06 18:29   ppt/slideLayouts/_rels/slideLay
      311  2017-07-06 18:27   ppt/slideLayouts/_rels/slideLay |       311  2017-07-06 18:29   ppt/slideLayouts/_rels/slideLay
      311  2017-07-06 18:27   ppt/slideLayouts/_rels/slideLay |       311  2017-07-06 18:29   ppt/slideLayouts/_rels/slideLay
      311  2017-07-06 18:27   ppt/slideLayouts/_rels/slideLay |       311  2017-07-06 18:29   ppt/slideLayouts/_rels/slideLay
      311  2017-07-06 18:27   ppt/slideLayouts/_rels/slideLay |       311  2017-07-06 18:29   ppt/slideLayouts/_rels/slideLay
      311  2017-07-06 18:27   ppt/slideLayouts/_rels/slideLay |       311  2017-07-06 18:29   ppt/slideLayouts/_rels/slideLay
      311  2017-07-06 18:27   ppt/slideLayouts/_rels/slideLay |       311  2017-07-06 18:29   ppt/slideLayouts/_rels/slideLay
        0  2017-07-06 18:27   ppt/slideLayouts/_rels/./       |         0  2017-07-06 18:29   ppt/slideLayouts/_rels/./
     4723  2017-07-06 18:27   ppt/slideLayouts/slideLayout2.x |      4723  2017-07-06 18:29   ppt/slideLayouts/slideLayout2.x
     4274  2017-07-06 18:27   ppt/slideLayouts/slideLayout3.x |      4274  2017-07-06 18:29   ppt/slideLayouts/slideLayout3.x
     4635  2017-07-06 18:27   ppt/slideLayouts/slideLayout8.x |      4635  2017-07-06 18:29   ppt/slideLayouts/slideLayout8.x
        0  2017-07-06 18:27   ppt/slideLayouts/./             |         0  2017-07-06 18:29   ppt/slideLayouts/./
      182  2017-07-06 18:27   ppt/tableStyles.xml             |       182  2017-07-06 18:29   ppt/tableStyles.xml
        0  2017-07-06 18:27   ppt/media/                      |         0  2017-07-06 18:29   ppt/media/
        0  2017-07-06 18:27   ppt/media/./                    |         0  2017-07-06 18:29   ppt/media/./
     1051  2017-07-06 18:27   ppt/viewProps.xml               |      1051  2017-07-06 18:29   ppt/viewProps.xml
        0  2017-07-06 18:27   ppt/slideMasters/               |         0  2017-07-06 18:29   ppt/slideMasters/
        0  2017-07-06 18:27   ppt/slideMasters/_rels/         |         0  2017-07-06 18:29   ppt/slideMasters/_rels/
     1991  2017-07-06 18:27   ppt/slideMasters/_rels/slideMas |      1991  2017-07-06 18:29   ppt/slideMasters/_rels/slideMas
        0  2017-07-06 18:27   ppt/slideMasters/_rels/./       |         0  2017-07-06 18:29   ppt/slideMasters/_rels/./
    17838  2017-07-06 18:27   ppt/slideMasters/slideMaster1.x |     17838  2017-07-06 18:29   ppt/slideMasters/slideMaster1.x
        0  2017-07-06 18:27   ppt/slideMasters/./             |         0  2017-07-06 18:29   ppt/slideMasters/./
        0  2017-07-06 18:27   ppt/_rels/                      |         0  2017-07-06 18:29   ppt/_rels/
     1299  2017-07-06 18:27   ppt/_rels/presentation.xml.rels |      1299  2017-07-06 18:29   ppt/_rels/presentation.xml.rels
        0  2017-07-06 18:27   ppt/_rels/./                    |         0  2017-07-06 18:29   ppt/_rels/./
      886  2017-07-06 18:27   ppt/presProps.xml               |       886  2017-07-06 18:29   ppt/presProps.xml
        0  2017-07-06 18:27   ppt/theme/                      |         0  2017-07-06 18:29   ppt/theme/
     7004  2017-07-06 18:27   ppt/theme/theme1.xml            |      7004  2017-07-06 18:29   ppt/theme/theme1.xml
        0  2017-07-06 18:27   ppt/theme/./                    |         0  2017-07-06 18:29   ppt/theme/./
        0  2017-07-06 18:27   ppt/./                          |         0  2017-07-06 18:29   ppt/./
        0  2017-07-06 18:27   docProps/                       |         0  2017-07-06 18:29   docProps/
      570  2017-07-06 18:27   docProps/core.xml               |       570  2017-07-06 18:29   docProps/core.xml
     1686  2017-07-06 18:27   docProps/app.xml                |      1686  2017-07-06 18:29   docProps/app.xml
        0  2017-07-06 18:27   docProps/./                     |         0  2017-07-06 18:29   docProps/./
        0  2017-07-06 18:27   _rels/                          |         0  2017-07-06 18:29   _rels/
      607  2017-07-06 18:27   _rels/.rels                     |       607  2017-07-06 18:29   _rels/.rels
        0  2017-07-06 18:27   _rels/./                        |         0  2017-07-06 18:29   _rels/./
```

**Comment by danielsousaio** [comment]
# Update

After messing around with diffs between a file generated with your version and a file generated with my fork/feature I found a interesting difference.

### Unzipped each powerpoint file to a directory:
```
➜ tree -L 2
.
├── bad
│   ├── bad.pptx
│   ├── [Content_Types].xml
│   ├── docProps
│   ├── ppt
│   └── _rels
├── bad.pptx
├── good
│   ├── [Content_Types].xml
│   ├── docProps
│   ├── good.pptx
│   ├── ppt
│   └── _rels
└── good.pptx
```

### On vim, ran [DirDiff](https://github.com/will13/vim-dirdiff):
```
:DirDiff bad good
```
Found a diff in `ppt/slides/_rels/slide2.xml.rels`:
```
--  <Relationship Id="rId1" Target="../slideLayouts/slideLayout1.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout"/>
++  <Relationship Id="rId1" Target="../slideLayouts/slideLayout2.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout"/>
```
Seems like the problem is not on the third slide, but actually on the slide before it which calls a different layout file.

If I hardcode `slideLayout1.xml` instead of `slideLayout<%= index %>.xml` the problem is solved.

Anyways, why is the index different on each file? And why does the layout needs to change with index?

## Summary

Somehow, 2nd slide is using the wrong slideLayout.

**Comment by danielsousaio** [comment]
## Kind of a solution

As mentioned above, always having **slideLayout1** works well. Doing this as a suggestion, please give your feedback. Please check [a6d2943](https://github.com/pythonicrubyist/powerpoint/pull/19/commits/a6d29435487de1d01ae35e060952a568d53d5c17).

**Comment by hrangel** [comment]
Any news about a merge?

**Comment by danielsousaio** [comment]
@hrangel I needed those features for a project so in the meanwhile I created a new gem based on this one with the added features of tables and charts. Feel free to visit it: https://github.com/danielsousaio/ruby_slides

**Comment by pythonicrubyist** [comment]
@danielsousaio  thanks for your contribution. Since you have published a new gem, I would rather not merge this PR. People who need this feature, can use your new gem at https://github.com/danielsousaio/ruby_slides . Great job! 👍

**Pull request closed without merging**
